[tool.poetry]
name = "ice-breaker-course-reference"
version = "0.1.0"
description = ""
authors = ["Nhan Nguyen <nhan.nguyen@27global.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
